AllCops:
  # Include gemspec and Rakefile
  Include:
    - "lib/**/*.rb"
    - "lib/**/*.rake"
    - "spec/**/*.rb"
  Exclude:
    - "bin/**/*"
    - "lib/localer/ext/*.rb"
    - "Appraisals"
    - "Gemfile"
    - "Rakefile"
    - "*.gemspec"
    - "spec/dummy_app/"
  DisplayCopNames: true
  NewCops: enable
  StyleGuideCopsOnly: false

Naming/AccessorMethodName:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Style/Documentation:
  Exclude:
    - "spec/**/*.rb"

Style/StringLiterals:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - "spec/**/*.rb"

Style/DoubleNegation:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Layout/SpaceInsideStringInterpolation:
  EnforcedStyle: no_space

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - "spec/**/*.rb"

Layout/LineLength:
  Max: 120
  Exclude:
    - "spec/**/*.rb"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"

Security/YAMLLoad:
  Enabled: false
