name: Build

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      VERIFY_RESERVED: 1
      CI: true
      CUCUMBER_PUBLISH_QUIET: true
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.7, 2.6, 2.5, 2.4]
        gemfile: [
          'gemfiles/rails50.gemfile',
          'gemfiles/rails51.gemfile',
          'gemfiles/rails52.gemfile',
          'gemfiles/rails60.gemfile',
          'gemfiles/rails61.gemfile'
        ]
        exclude:
        - ruby: 2.4
          gemfile: gemfiles/rails52.gemfile
        - ruby: 2.4
          gemfile: gemfiles/rails60.gemfile
        - ruby: 2.4
          gemfile: gemfiles/rails61.gemfile


    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: /home/runner/bundle
        key: bundle-${{ matrix.ruby }}-${{ matrix.gemfile }}-${{ hashFiles(matrix.gemfile) }}-${{ hashFiles('**/*.gemspec') }}
        restore-keys: |
          bundle-${{ matrix.ruby }}-${{ matrix.gemfile }}-
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Bundle install
      run: |
        bundle config path /home/runner/bundle
        bundle config --global gemfile ${{ matrix.gemfile }}
        bundle install
        bundle update
    - name: Run tests
      run: bundle exec rake
